version: "3"
services:

  prometheus:
    image: prom/prometheus
    container_name: "prometheus"
    privileged: true
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
#    ports:
#      - '9090:9090'
    network_mode: "host"
    depends_on:
      - pushgateway

  pushgateway:
    image: prom/pushgateway
    container_name: "pushgateway"
    network_mode: "host"
#    ports:
#      - '9091:9091'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
#    ports:
#      - "3000:3000"
    volumes:
      - grafanadata:/var/lib/grafana
    network_mode: "host"
    depends_on:
      - prometheus

volumes:
  promdata:
  grafanadata: